/**
 * Seed therapist profiles.
 *
 * These records are used to pre-populate the database the first time the
 * application starts (see the auto-seed logic in the API routes).  All
 * coordinates are real clinic-area coordinates so that Haversine distance
 * calculations are accurate when the user shares their location.
 *
 * Cities covered: Mumbai, Bangalore, Delhi, Hyderabad, Chennai, Pune.
 */

import type { Therapist } from "@/types/therapist.types";

type SeedTherapist = Omit<Therapist, "id">;

export const THERAPIST_SEED_DATA: SeedTherapist[] = [
  // ── Mumbai ──────────────────────────────────────────────────────────────────
  {
    name: "Dr. Meera Kapoor",
    title: "Clinical Psychologist",
    specializations: ["Depression", "Anxiety", "Trauma"],
    credentials: "PhD Psychology, RCI Registered",
    languages: ["English", "Hindi", "Marathi"],
    experience: "11 years",
    bio: "Expert in cognitive-behavioural therapy for depression and trauma recovery with a compassionate, evidence-based approach.",
    avatar: "MK",
    email: "dr.kapoor@mindwell.in",
    phone: "+91 98200 11234",
    clinicName: "MindWell Wellness Centre",
    clinicAddress: "12 Wellness Plaza, Andheri West",
    city: "Mumbai",
    coordinates: { lat: 19.1196, lng: 72.8468 },
    available: true,
    nextAvailable: "Today, 4:00 PM",
    availabilitySlots: [
      { day: "Monday", startTime: "09:00", endTime: "17:00" },
      { day: "Wednesday", startTime: "09:00", endTime: "17:00" },
      { day: "Friday", startTime: "09:00", endTime: "13:00" },
    ],
    fee: "₹1200",
    rating: 4.9,
    reviews: 134,
  },
  {
    name: "Dr. Vikram Nair",
    title: "Psychiatrist",
    specializations: ["Bipolar", "Schizophrenia", "Mood Disorders"],
    credentials: "MD Psychiatry, DPM",
    languages: ["English", "Hindi", "Malayalam"],
    experience: "14 years",
    bio: "Specialist in pharmacological and psychotherapy-based treatment for mood and psychotic disorders.",
    avatar: "VN",
    email: "dr.nair@healingminds.in",
    phone: "+91 99876 54321",
    clinicName: "Healing Minds Clinic",
    clinicAddress: "8 Serenity Towers, Bandra East",
    city: "Mumbai",
    coordinates: { lat: 19.0607, lng: 72.853 },
    available: true,
    nextAvailable: "Today, 6:30 PM",
    availabilitySlots: [
      { day: "Tuesday", startTime: "10:00", endTime: "18:00" },
      { day: "Thursday", startTime: "10:00", endTime: "18:00" },
      { day: "Saturday", startTime: "10:00", endTime: "14:00" },
    ],
    fee: "₹1500",
    rating: 4.8,
    reviews: 98,
  },
  {
    name: "Ms. Pooja Desai",
    title: "Counselling Psychologist",
    specializations: ["Stress", "Burnout", "Relationships"],
    credentials: "MPhil Clinical Psychology, RCI Registered",
    languages: ["English", "Hindi", "Gujarati"],
    experience: "7 years",
    bio: "Helping professionals overcome burnout and rebuild meaningful relationships through compassion-focused therapy.",
    avatar: "PD",
    email: "pooja.desai@mindbridge.in",
    phone: "+91 91234 67890",
    clinicName: "MindBridge Counselling",
    clinicAddress: "3 Hope Lane, Powai",
    city: "Mumbai",
    coordinates: { lat: 19.1176, lng: 72.906 },
    available: false,
    nextAvailable: "Tomorrow, 10:00 AM",
    availabilitySlots: [
      { day: "Monday", startTime: "14:00", endTime: "19:00" },
      { day: "Wednesday", startTime: "14:00", endTime: "19:00" },
    ],
    fee: "₹900",
    rating: 4.7,
    reviews: 67,
  },
  // ── Bangalore ───────────────────────────────────────────────────────────────
  {
    name: "Dr. Priya Sharma",
    title: "Clinical Psychologist",
    specializations: ["Depression", "Anxiety", "Stress"],
    credentials: "PhD Psychology, CBT Certified",
    languages: ["English", "Hindi", "Kannada"],
    experience: "8 years",
    bio: "Specialising in cognitive-behavioural therapy for depression and anxiety disorders with a warm, collaborative style.",
    avatar: "PS",
    email: "priya.sharma@innermind.in",
    phone: "+91 98441 23456",
    clinicName: "InnerMind Therapy",
    clinicAddress: "45 MG Road, Shivaji Nagar",
    city: "Bangalore",
    coordinates: { lat: 12.9716, lng: 77.5946 },
    available: true,
    nextAvailable: "Today, 3:00 PM",
    availabilitySlots: [
      { day: "Monday", startTime: "09:00", endTime: "18:00" },
      { day: "Tuesday", startTime: "09:00", endTime: "18:00" },
      { day: "Thursday", startTime: "09:00", endTime: "18:00" },
    ],
    fee: "₹800",
    rating: 4.9,
    reviews: 142,
  },
  {
    name: "Dr. Arjun Mehta",
    title: "Psychiatrist",
    specializations: ["PTSD", "Trauma", "Bipolar"],
    credentials: "MD Psychiatry, EMDR Certified",
    languages: ["English", "Hindi", "Gujarati"],
    experience: "12 years",
    bio: "Expert in trauma-focused therapy and EMDR for PTSD recovery.",
    avatar: "AM",
    email: "arjun.mehta@traumacare.in",
    phone: "+91 97401 88765",
    clinicName: "TraumaCare Centre",
    clinicAddress: "22 Residency Road, Richmond Town",
    city: "Bangalore",
    coordinates: { lat: 12.9698, lng: 77.6078 },
    available: true,
    nextAvailable: "Tomorrow, 10:00 AM",
    availabilitySlots: [
      { day: "Wednesday", startTime: "10:00", endTime: "17:00" },
      { day: "Friday", startTime: "10:00", endTime: "17:00" },
    ],
    fee: "₹1000",
    rating: 4.8,
    reviews: 98,
  },
  // ── Delhi ────────────────────────────────────────────────────────────────────
  {
    name: "Dr. Rahul Singh",
    title: "Clinical Psychologist",
    specializations: ["OCD", "Phobias", "Stress"],
    credentials: "PhD Clinical Psychology, ERP Specialist",
    languages: ["English", "Hindi"],
    experience: "10 years",
    bio: "Specialist in exposure therapy for OCD and specific phobias using evidence-based ERP protocols.",
    avatar: "RS",
    email: "rahul.singh@mindspace.in",
    phone: "+91 98110 34567",
    clinicName: "MindSpace Delhi",
    clinicAddress: "15 Connaught Place, New Delhi",
    city: "Delhi",
    coordinates: { lat: 28.6315, lng: 77.2167 },
    available: true,
    nextAvailable: "Today, 5:30 PM",
    availabilitySlots: [
      { day: "Monday", startTime: "11:00", endTime: "19:00" },
      { day: "Thursday", startTime: "11:00", endTime: "19:00" },
      { day: "Saturday", startTime: "09:00", endTime: "13:00" },
    ],
    fee: "₹900",
    rating: 4.9,
    reviews: 123,
  },
  // ── Hyderabad ────────────────────────────────────────────────────────────────
  {
    name: "Ms. Ananya Iyer",
    title: "Counselling Psychologist",
    specializations: ["Adolescents", "Depression", "Academic Stress"],
    credentials: "MSc Psychology, Child & Adolescent Therapy",
    languages: ["English", "Telugu", "Hindi"],
    experience: "6 years",
    bio: "Dedicated to supporting young adults and adolescents through academic pressure and personal challenges.",
    avatar: "AI",
    email: "ananya.iyer@youthminds.in",
    phone: "+91 99890 56789",
    clinicName: "YouthMinds Counselling",
    clinicAddress: "7 Jubilee Hills Road No. 36",
    city: "Hyderabad",
    coordinates: { lat: 17.4315, lng: 78.4075 },
    available: true,
    nextAvailable: "Today, 4:00 PM",
    availabilitySlots: [
      { day: "Tuesday", startTime: "09:00", endTime: "17:00" },
      { day: "Wednesday", startTime: "09:00", endTime: "17:00" },
      { day: "Friday", startTime: "09:00", endTime: "17:00" },
    ],
    fee: "₹700",
    rating: 4.8,
    reviews: 89,
  },
  // ── Pune ─────────────────────────────────────────────────────────────────────
  {
    name: "Dr. Suresh Patel",
    title: "Psychotherapist",
    specializations: ["Addiction", "Grief", "Life Transitions"],
    credentials: "PhD Psychology, CRAFT Certified",
    languages: ["English", "Hindi", "Marathi"],
    experience: "15 years",
    bio: "Extensive experience helping individuals through addiction recovery, grief, and major life transitions.",
    avatar: "SP",
    email: "suresh.patel@hopepath.in",
    phone: "+91 98220 90123",
    clinicName: "HopePath Therapy Centre",
    clinicAddress: "33 FC Road, Deccan Gymkhana",
    city: "Pune",
    coordinates: { lat: 18.5204, lng: 73.8567 },
    available: false,
    nextAvailable: "Thu, 11:00 AM",
    availabilitySlots: [
      { day: "Thursday", startTime: "11:00", endTime: "18:00" },
      { day: "Saturday", startTime: "10:00", endTime: "15:00" },
    ],
    fee: "₹1200",
    rating: 4.9,
    reviews: 201,
  },
  // ── Chennai ──────────────────────────────────────────────────────────────────
  {
    name: "Ms. Kavita Reddy",
    title: "Counselling Psychologist",
    specializations: ["Relationships", "Self-esteem", "Anxiety"],
    credentials: "MSc Psychology, RCI Registered",
    languages: ["English", "Telugu", "Tamil"],
    experience: "5 years",
    bio: "Helping individuals build healthier relationships and improve self-worth through person-centred therapy.",
    avatar: "KR",
    email: "kavita.reddy@soulcare.in",
    phone: "+91 97890 12345",
    clinicName: "SoulCare Wellness",
    clinicAddress: "18 Anna Salai, Teynampet",
    city: "Chennai",
    coordinates: { lat: 13.0418, lng: 80.2341 },
    available: false,
    nextAvailable: "Wed, 2:00 PM",
    availabilitySlots: [
      { day: "Wednesday", startTime: "14:00", endTime: "19:00" },
      { day: "Friday", startTime: "14:00", endTime: "19:00" },
    ],
    fee: "₹600",
    rating: 4.7,
    reviews: 67,
  },
];
